

var buffer = CircularBuffer<Int>(capacity: 4)
buffer.read()
print(buffer)
buffer.write(newElement: 1)
print(buffer)
buffer.write(newElement: 2)
buffer.write(newElement: 3)
buffer.write(newElement: 4)
buffer.write(newElement: 5)

print(buffer)
buffer.read()
print(buffer)
buffer.write(newElement: 5)
buffer.read()
buffer.write(newElement: 6)
print(buffer)
print(buffer.storageSpace)
buffer.read()
buffer.read()
buffer.read()
buffer.read()
buffer.read()
print(buffer)
print(buffer.storageSpace)
